name: Feature Request
description: Request a new or improved a feature in Kairo UI
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Please search GitHub for a similar [issue](https://github.com/kairo-sh/kairo-ui/issues) or [PR](https://github.com/kairo-sh/kairo-ui/pulls) before submitting a new issue.

  - type: textarea
    id: information
    attributes:
      label: Information
      description: Tell us what you want to be added to Kairo UI
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe any alternatives/workarounds you're currently using

  - type: checkboxes
    id: assistance
    attributes:
      label: I would be willing to submit a PR to fix this issue
      description: Assistance is provided if you need help submitting a pull request
      options:
        - label: 'Yes'
        - label: 'No'
